CREATE TABLE IF NOT EXISTS tunnels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  remote_port INT NOT NULL,
  local_host VARCHAR(255) NOT NULL,
  local_port INT NOT NULL,
  pid INT
);

CREATE TABLE IF NOT EXISTS proxies (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  upstream VARCHAR(255) NOT NULL,
  match VARCHAR(255) NOT NULL
);